package main;

import errors.*;
import environment.*;
import type.*;
import beaver.*;
import node.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "Parser.grammar".
 */
public class Parser extends beaver.Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjM0cOLUCR$vrppp0ePgGqP90qBKhPAgHDMgY8CgQfQ3Cqb7#BVO#Y8dkq8PMqI6bNYao" +
		"fL2A92l7Flk$hwtU##zvxppbtSMzvF8z7TvxVVTVl$TxlEzzzl$SCa5K5XJWOvw8jpiHPQ8" +
		"xUg83vs1VxeHpAOtySW1paua0SX8geX8cu3QDm3sx14DoEeHY6Et04gcBlNOhoa2TARop6n" +
		"GcYx9CqokxvbcRWUta6ll$BmFUw37pd9lLjWHFG4Erm4jgZ0yx6ENWTCxZ7ip0JJyjsvE5K" +
		"d1ADTJt6uX8CG2TSW69qHm$qIn3XVcHZ96pv14ynmc7#238aZGWZKUAEna8iOeJdi9GpDq4" +
		"8ez6ONEKq8joBHt0dXcE4$C48XmTMSNuwESXsayDgD6645ypCJP2bEQp890VinGX71dBeaj" +
		"O#tEJ9OJqQY#16dCOSpiWq1zdC24S5SZWzZGWtupoinHGyZpwCq34GONPSX7mSxVDnV#5LS" +
		"2YgeJfjXw06Qk4Or4Kz7EUpRSLcdoqV9sCUBaChjCGcN1M8CpXfd0de5eXp9Pv5Crp3DSp6" +
		"rO4u5oMDauzUAMpZKjYkJMeRXAa#srJqfNz1Ylsw8iKyToMrlH7Oo$Yd6gcY3tkgwAsu6$V" +
		"XGJmW2wBsnppsYExb1BgD2NHRFBhu3FPe$ksQI7KQGsw2gVRpyGpvqKOxFiezphFwA6lM3N" +
		"W2hNdcH#jPdUIfa37koOJQchxVI6sVLCSd7UkJwlkauttIYJwfWKzgv9EQ#gGsFgaGdNrIa" +
		"KVgwlEyq2Vrz4cN#gJ#FccWJteDYxYVxfsu4WwvQR9JzpCV2vIRRAf0H4jUrc2bh4M#lA7Q" +
		"AK4Fl8Jfc4EF$uUrz0vwh9KFU0laymbwjM5#YMnGRWsMuKKiPtPbM2MlK7u56x0Eh#9j$hq" +
		"fFm5uYxNz5AwgCU#o9jpTPbnN2zv6BNcljU8PQQEhRHSzQntPqPp7UwOpx#v2tZPkFrEysr" +
		"7S4Pb5sUCRzhLWinzps0$jnVuzczrp8zx#aJtE2SIgp1Dz2E#cAkm6yzcD7S5kA3v2FzvN5" +
		"li9LniVOL0Q4In6S3MzsFNcy8sWXEDgS2NbMJ4giqxyTOIgx96giOEfpl7nEUIcbKEEqNJX" +
		"p3diHMgR7Ffg3dt#eHoA0Zc0zSPY3db$ImwXD28KCDEwx47g9OnGFow27V3nlh7OvesbWhw" +
		"p7EopNSWUpckpkSRklAK6i6vUJiuVfpHf72imXyspLC1xfo7NK9zzQBhvfBQTaC9MaDIMm#" +
		"oyDejtL#hzQf1YdcFJtilufvgeYkRIhmQxp9hS#KJstT4bEjjxDFzsJRWw7K$ECboULYUNx" +
		"n7bSirleZpVWKBy3RhQy5ajybId66SbrFf$8$zboRqJRNCdMkmstIfGK$VJZlxVASzKWOZM" +
		"vVFedKS#HxMruZngyKaLaQ#PD4PTskgHjtpQC9$Blp1diLlEuvEsU6iL61gM2ymfgOCw8lG" +
		"5jjq4yva5M5M8buXcnAt4aTI$Gxh0zTaLS6nv85G1iFUEwKASX$KGeQC1Xpc4wgg#WTAcr2" +
		"yaRKFw8sb7qgMaNKXNaFOYNKzw6Uacqi6axvBUIBgJT1ZfRwJta7vD#WZdh#Z9gGEnKEUQI" +
		"5jjZsqhvOsa4zN#1J6TkWb$lLPx1iUzf#Fcac#h#iMKcRyrGcqhgMka$0Ro7PJVGhwhvi5r" +
		"MCs9o9xjeAqlvPx4ByGGrNzA$TMK9wdy7UMXbBa$TdMT$p2bxjWovHyYnkjSgubQb3Ubyqn" +
		"r$Dt4pe1k6UFiHxgSc4##LEFFrDoOanEYhNLiJEXpudVghR3i74HK9cQhN2FcwznBxF383n" +
		"ESqrcdyi#CVGpd#z2VbxDAy#YcyhTAkLTPsSG#v9SGtwYUpokhdF8V4NOiLXRFSrOEmNFhl" +
		"4xmMJWy8qwsnwSYKKd7y$auxfXzLVuiviVtT#1xwZgvlnDN9o9b9ENIUGQfmC#yWBnPzo1F" +
		"QHUbuvHk25Ex94n3lsY#aUUIhVG0fP7rwTbogYcjhVIuvBavZU9rrjA0JzFCr#oq2iZjFNm" +
		"d3r$iuNjwnt3$FoQfghPBmnGDbRPN$HKgzrBvAbq3VylM9kK$ZSs1Qy8qD8dwpfwvoZ9TO#" +
		"9rOumt$x3E7k6ninw6fld7s6FzScZ5hitjZDGvHWLoMgFKJZ1cHfXQbGBwEPxy9WTiStLCe" +
		"STdLentxosxhyUsA7vURECE$IxRuVb8cQoG5#K5MIxBv7bPAalaENbQPieCcIx3ZSTYUPpV" +
		"OmZU8yAQ8wE91ua7YFk9#mZM9k5z8wC8raPXVPMxpFYHCiAD98yPwL6vKoOORg7vdYVZPPo" +
		"CbJjac0oLs#KscKl$HRGCbsUDnt2PO#Xiy$sC#PwbsQzK#XGnJVcfqRKzAK$85CFnbfDjib" +
		"NrRycFyeDyBz$9j$ADV2rVoPV26YOVoUVocMTlFYJULtw7lAVSEqfPsMIBl6duZ#LTrRwjT" +
		"99C5ZuJuVqihn4RvTLetFNcUxNvNYKlm$UHTSAwAh$9hogpgWkhBAx587Qyl0DnYO7Dzr4N" +
		"5j#p7BvfMNpJIOnE7fn3T5PqvBYp6UjSzaKkpcTFtO$w20eP$mBwz2VjJxa7UVP6XCqkseN" +
		"5Jjin$NUHwGD1MEp$t1xGOeze6$GcVp5HmgwzX6leIhuRVRkHzk7OFgPB2w4vOnNJlvXo2y" +
		"NfAN06$LlH$rJIWOmtaBe1Z3E0j3Lf6w8jSIPn5j6IUY$QSRtjEBOzqO6vbTAdbFhkbDbR4" +
		"I7skZOxtX3xNeVzh#N3oTJxOIVG9VEnecYQ08F$1D9WL0W=");
 
	static class Events extends beaver.Parser.Events {
		public void syntaxError(Symbol token) {
			System.err.format("*** Erreur de syntaxe en ligne %d, colonne %d. Token inattendu: %s\n",
				Symbol.getLine(token.getStart()),
				Symbol.getColumn(token.getStart()),
				Terminals.NAMES[token.getId()]);
		}
	}
	
	public void semanticError(String msg, Symbol token) {
		System.err.format("*** " + msg + " ligne %d, colonne %d\n",
			Symbol.getLine(token.getStart()),
			Symbol.getColumn(token.getStart()));
	}
	
	/*
	 * Environnements disponibles pour la gestion des types complexes, des variables et des fonctions.
	 */
	private Environment typeEnvironment = new Environment("types", 0, 0);
	private Environment procedureEnvironment = new Environment("procedures", 0, 0);
	private StackEnvironment stackEnvironment = new StackEnvironment("local_variables_stack");
	private String type_declaration_name;
	
	public void backtrace() 
	{
		typeEnvironment.backtrace();
		procedureEnvironment.backtrace();
		stackEnvironment.backtrace();
	}

	private final Action[] actions;

	public Parser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] program = type_declaration_part.tydec variable_declaration_part.vardec procedure_definition_part.procdec empty_main TOKEN_BEGIN statement_list.stmn TOKEN_END
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_tydec = _symbols[offset + 1];
					final NodeList tydec = (NodeList) _symbol_tydec.value;
					final Symbol _symbol_vardec = _symbols[offset + 2];
					final NodeList vardec = (NodeList) _symbol_vardec.value;
					final Symbol _symbol_procdec = _symbols[offset + 3];
					final NodeList procdec = (NodeList) _symbol_procdec.value;
					final Symbol _symbol_stmn = _symbols[offset + 6];
					final Node stmn = (Node) _symbol_stmn.value;
					 stackEnvironment.popEnvironment(); return new NodeList(tydec,vardec,procdec,stmn);
				}
			},
			new Action() {	// [1] empty_main = 
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 stackEnvironment.pushEnvironment("Main"); return new TypeVoid();
				}
			},
			Action.NONE,  	// [2] type_declaration_part = 
			new Action() {	// [3] type_declaration_part = TOKEN_TYPE type_declaration_list.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 2];
					final NodeList n = (NodeList) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [4] type_declaration_list = type_declaration_list.list type_declaration.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final NodeList list = (NodeList) _symbol_list.value;
					final Symbol _symbol_node = _symbols[offset + 2];
					final NodeId node = (NodeId) _symbol_node.value;
					 list.add(node); return list;
				}
			},
			new Action() {	// [5] type_declaration_list = type_declaration.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final NodeId node = (NodeId) _symbol_node.value;
					 return new NodeList(node);
				}
			},
			new Action() {	// [6] type_declaration = type_declaration_head.tname TOKEN_AFF type.ty TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_tname = _symbols[offset + 1];
					final IdentifierList tname = (IdentifierList) _symbol_tname.value;
					final Symbol _symbol_ty = _symbols[offset + 3];
					final Type ty = (Type) _symbol_ty.value;
					 	NodeId node = new NodeId(tname.first(), ty); typeEnvironment.putVariable(tname.first(), node); 
																	return node;
				}
			},
			new Action() {	// [7] type_declaration_head = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					 return new IdentifierList(name);
				}
			},
			new Action() {	// [8] type = simple_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Type n = (Type) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [9] type = named_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Type n = (Type) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [10] type = index_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Type n = (Type) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [11] type = array_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final TypeArray n = (TypeArray) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [12] type = pointer_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final TypePointer n = (TypePointer) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [13] type = structure_type.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final TypeStruct n = (TypeStruct) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [14] simple_type = TOKEN_STRING
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeString();
				}
			},
			new Action() {	// [15] simple_type = TOKEN_INTEGER
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeInt();
				}
			},
			new Action() {	// [16] simple_type = TOKEN_BOOLEAN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeBoolean();
				}
			},
			new Action() {	// [17] named_type = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					 return typeEnvironment.getVariable(name).getType();
				}
			},
			new Action() {	// [18] index_type = enumerated_type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeTuple t = (TypeTuple) _symbol_t.value;
					 return t;
				}
			},
			new Action() {	// [19] index_type = subrange_type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeArrayRange t = (TypeArrayRange) _symbol_t.value;
					 return t;
				}
			},
			new Action() {	// [20] enumerated_type = init_enumerated_type.t TOKEN_LPAR identifier_list.list TOKEN_RPAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeEnumRange t = (TypeEnumRange) _symbol_t.value;
					final Symbol _symbol_list = _symbols[offset + 3];
					final IdentifierList list = (IdentifierList) _symbol_list.value;
					 
																			TypeTuple tuple = new TypeTuple();
																			int i = 0;
																			for(String s : list)
																			{
																				TypeItemEnum tmp = new TypeItemEnum(i++, s);
																				stackEnvironment.putVariable(s, new NodeId(s, tmp));
																				tuple.add(tmp);
																			}
																			return tuple;
				}
			},
			new Action() {	// [21] init_enumerated_type = 
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeEnumRange();
				}
			},
			new Action() {	// [22] subrange_type = TOKEN_LIT_INTEGER.int1 TOKEN_DOTDOT TOKEN_LIT_INTEGER.int2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol int1 = _symbols[offset + 1];
					final Symbol int2 = _symbols[offset + 3];
					 return new TypeArrayRange(new TypeInt(int1), new TypeInt(int2));
				}
			},
			new Action() {	// [23] subrange_type = TOKEN_IDENTIFIER.name1 TOKEN_DOTDOT TOKEN_IDENTIFIER.name2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name1 = _symbols[offset + 1];
					final Symbol name2 = _symbols[offset + 3];
					 return new TypeArrayRange(
																						stackEnvironment.getVariable(name1).getType(),
																						stackEnvironment.getVariable(name2).getType());
				}
			},
			new Action() {	// [24] array_type = TOKEN_ARRAY TOKEN_LBRACKET range_type.r TOKEN_RBRACKET TOKEN_OF type.ty
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_r = _symbols[offset + 3];
					final Type r = (Type) _symbol_r.value;
					final Symbol _symbol_ty = _symbols[offset + 6];
					final Type ty = (Type) _symbol_ty.value;
					 return new TypeArray(r, ty);
				}
			},
			new Action() {	// [25] range_type = enumerated_type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeTuple t = (TypeTuple) _symbol_t.value;
					 return t;
				}
			},
			new Action() {	// [26] range_type = subrange_type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeArrayRange t = (TypeArrayRange) _symbol_t.value;
					 return t;
				}
			},
			new Action() {	// [27] range_type = named_type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final Type t = (Type) _symbol_t.value;
					 return t;
				}
			},
			new Action() {	// [28] pointer_type = TOKEN_CIRC type.ty
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_ty = _symbols[offset + 2];
					final Type ty = (Type) _symbol_ty.value;
					 return new TypePointer(ty);
				}
			},
			new Action() {	// [29] structure_type = TOKEN_STRUCT TOKEN_LBRACE feature_list_type.list TOKEN_RBRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 3];
					final TypeFeatureList list = (TypeFeatureList) _symbol_list.value;
					 return new TypeStruct(list);
				}
			},
			new Action() {	// [30] feature_list_type = feature_list_type.list feature_type.f
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final TypeFeatureList list = (TypeFeatureList) _symbol_list.value;
					final Symbol _symbol_f = _symbols[offset + 2];
					final TypeFeature f = (TypeFeature) _symbol_f.value;
					 list.add(f); return list;
				}
			},
			new Action() {	// [31] feature_list_type = feature_type.f
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_f = _symbols[offset + 1];
					final TypeFeature f = (TypeFeature) _symbol_f.value;
					 return new TypeFeatureList(f);
				}
			},
			new Action() {	// [32] feature_type = TOKEN_IDENTIFIER.name TOKEN_COLON type.t TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					final Symbol _symbol_t = _symbols[offset + 3];
					final Type t = (Type) _symbol_t.value;
					 return new TypeFeature(name, t);
				}
			},
			Action.NONE,  	// [33] variable_declaration_part = 
			new Action() {	// [34] variable_declaration_part = TOKEN_VAR variable_declaration_list.list
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 2];
					final Node list = (Node) _symbol_list.value;
					 return list;
				}
			},
			new Action() {	// [35] variable_declaration_list = variable_declaration_list.list variable_declaration.dec
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final Node list = (Node) _symbol_list.value;
					final Symbol _symbol_dec = _symbols[offset + 2];
					final Node dec = (Node) _symbol_dec.value;
					 list.add(dec); return list;
				}
			},
			new Action() {	// [36] variable_declaration_list = variable_declaration.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final Node node = (Node) _symbol_node.value;
					 return new NodeList(node);
				}
			},
			new Action() {	// [37] variable_declaration = identifier_list.list TOKEN_COLON type.ty TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final IdentifierList list = (IdentifierList) _symbol_list.value;
					final Symbol _symbol_ty = _symbols[offset + 3];
					final Type ty = (Type) _symbol_ty.value;
					 	
																NodeList node_list = new NodeList();
																for(String s : list) 
																{
															         NodeId node = new NodeId(s, ty);
															         stackEnvironment.putVariable(s, node); /* TODO Verif enum (in typeEnvironment)*/
															         node_list.add(node);
														      	} 
														      	return node_list;
				}
			},
			new Action() {	// [38] identifier_list = identifier_list.list TOKEN_COMMA TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final IdentifierList list = (IdentifierList) _symbol_list.value;
					final Symbol name = _symbols[offset + 3];
					 list.add(name); return list;
				}
			},
			new Action() {	// [39] identifier_list = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					 return new IdentifierList(name.getStart(), name.getEnd(), name);
				}
			},
			Action.NONE,  	// [40] procedure_definition_part = 
			new Action() {	// [41] procedure_definition_part = procedure_definition_list.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [42] procedure_definition_list = procedure_definition_list.list procedure_definition.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final Node list = (Node) _symbol_list.value;
					final Symbol _symbol_node = _symbols[offset + 2];
					final Node node = (Node) _symbol_node.value;
					 list.add(node); return list;
				}
			},
			new Action() {	// [43] procedure_definition_list = procedure_definition.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final Node node = (Node) _symbol_node.value;
					 return new NodeList(node.getStart(), node.getEnd(), node);
				}
			},
			new Action() {	// [44] procedure_definition = procedure_definition_head.h block.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_h = _symbols[offset + 1];
					final NodeId h = (NodeId) _symbol_h.value;
					final Symbol _symbol_b = _symbols[offset + 2];
					final Node b = (Node) _symbol_b.value;
					 stackEnvironment.popEnvironment(); return new NodeList(h.getStart(), b.getEnd(), h,b);
				}
			},
			new Action() {	// [45] procedure_definition = procedure_declaration_head.h TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_h = _symbols[offset + 1];
					final NodeId h = (NodeId) _symbol_h.value;
					final Symbol e = _symbols[offset + 2];
					 stackEnvironment.popEnvironment(); h.setEnd(e); return h;
				}
			},
			new Action() {	// [46] procedure_definition_head = procedure_head.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final NodeId node = (NodeId) _symbol_node.value;
					 	try 
								{
									procedureEnvironment.putVariable(node.getName(), node);
								}
							 	catch (CustomError err)
							 	{
							 		//Cas deja defini, mais a remplacer
							 		procedureEnvironment.replaceVariable(node.getName(), node);
							 	}
							 	return node;
				}
			},
			new Action() {	// [47] procedure_declaration_head = procedure_head.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final NodeId node = (NodeId) _symbol_node.value;
					 procedureEnvironment.putVariable(node.getName(),  node); return node;
				}
			},
			new Action() {	// [48] procedure_head = TOKEN_PROCEDURE.b procedure_name.nid TOKEN_LPAR argt_part.args TOKEN_RPAR.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_nid = _symbols[offset + 2];
					final TypeNamed nid = (TypeNamed) _symbol_nid.value;
					final Symbol _symbol_args = _symbols[offset + 4];
					final TypeTuple args = (TypeTuple) _symbol_args.value;
					final Symbol e = _symbols[offset + 5];
					 	NodeId node = new NodeId(b.getStart(), e.getEnd(), nid.getName(), new TypeFunct(nid.getName(), args, new TypeVoid())); 
							return node;
				}
			},
			new Action() {	// [49] procedure_head = TOKEN_FUNCTION.b procedure_name.nid TOKEN_LPAR argt_part.args TOKEN_RPAR TOKEN_COLON type.ty
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_nid = _symbols[offset + 2];
					final TypeNamed nid = (TypeNamed) _symbol_nid.value;
					final Symbol _symbol_args = _symbols[offset + 4];
					final TypeTuple args = (TypeTuple) _symbol_args.value;
					final Symbol _symbol_ty = _symbols[offset + 7];
					final Type ty = (Type) _symbol_ty.value;
					 	NodeId node = new NodeId(b.getStart(), ty.getEnd(), nid.getName(), new TypeFunct(nid.getName(), args, ty)); 
							return node;
				}
			},
			new Action() {	// [50] procedure_name = TOKEN_IDENTIFIER.namefct
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol namefct = _symbols[offset + 1];
					 	stackEnvironment.pushEnvironment((String)namefct.value, namefct.getStart(), namefct.getEnd()); 
													return new TypeNamed(namefct.getStart(), namefct.getEnd(), namefct);
				}
			},
			Action.NONE,  	// [51] argt_part = 
			new Action() {	// [52] argt_part = argt_list.list
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final NodeList list = (NodeList) _symbol_list.value;
					
													TypeTuple type_params = new TypeTuple(list.getStart(), list.getEnd());
													for(Node n : list)
												         type_params.add(((NodeExp)n).getType());
											      	return type_params;
				}
			},
			new Action() {	// [53] argt_list = argt_list.list TOKEN_COMMA argt.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final NodeList list = (NodeList) _symbol_list.value;
					final Symbol _symbol_node = _symbols[offset + 3];
					final Node node = (Node) _symbol_node.value;
					 list.add(node); return list;
				}
			},
			new Action() {	// [54] argt_list = argt.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final Node node = (Node) _symbol_node.value;
					 return new NodeList(node);
				}
			},
			new Action() {	// [55] argt = TOKEN_IDENTIFIER.name TOKEN_COLON type.ty
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					final Symbol _symbol_ty = _symbols[offset + 3];
					final Type ty = (Type) _symbol_ty.value;
					 	NodeId node = new NodeId(name.getStart(), ty.getEnd(), (String)name.value, new TypeFeature (name, ty)); stackEnvironment.putVariable(name, node); 
													return node;
				}
			},
			new Action() {	// [56] block = variable_declaration_part.dec TOKEN_BEGIN statement_list.stmn TOKEN_END.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_dec = _symbols[offset + 1];
					final NodeList dec = (NodeList) _symbol_dec.value;
					final Symbol _symbol_stmn = _symbols[offset + 3];
					final Node stmn = (Node) _symbol_stmn.value;
					final Symbol e = _symbols[offset + 4];
					 return new NodeList(dec.getStart(), e.getEnd(), dec, stmn);
				}
			},
			new Action() {	// [57] statement_list = statement_list.list statement.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final Node list = (Node) _symbol_list.value;
					final Symbol _symbol_node = _symbols[offset + 2];
					final Node node = (Node) _symbol_node.value;
					 list.add(node); return list;
				}
			},
			new Action() {	// [58] statement_list = statement.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final Node node = (Node) _symbol_node.value;
					 return new NodeList(node.getStart(), node.getEnd(), node);
				}
			},
			new Action() {	// [59] statement = simple_statement.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final Node s = (Node) _symbol_s.value;
					 return s;
				}
			},
			new Action() {	// [60] statement = structured_statement.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [61] simple_statement = assignment_statement.a
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final NodeAssign a = (NodeAssign) _symbol_a.value;
					 return a;
				}
			},
			new Action() {	// [62] simple_statement = procedure_statement.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final Node s = (Node) _symbol_s.value;
					 return s;
				}
			},
			new Action() {	// [63] simple_statement = new_statement.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [64] simple_statement = dispose_statement.d
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_d = _symbols[offset + 1];
					final Node d = (Node) _symbol_d.value;
					 return d;
				}
			},
			new Action() {	// [65] simple_statement = println_statement.p
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_p = _symbols[offset + 1];
					final Node p = (Node) _symbol_p.value;
					 return p;
				}
			},
			new Action() {	// [66] simple_statement = readln_statement.r
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_r = _symbols[offset + 1];
					final Node r = (Node) _symbol_r.value;
					 return r;
				}
			},
			new Action() {	// [67] simple_statement = return_statement.r
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_r = _symbols[offset + 1];
					final NodeReturn r = (NodeReturn) _symbol_r.value;
					 return r;
				}
			},
			new Action() {	// [68] assignment_statement = variable_access.v TOKEN_AFF expression.exp TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final NodeExp v = (NodeExp) _symbol_v.value;
					final Symbol _symbol_exp = _symbols[offset + 3];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 4];
					 return new NodeAssign(v.getStart(), e.getEnd(), v, exp);
				}
			},
			new Action() {	// [69] procedure_statement = procedure_expression.exp TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_exp = _symbols[offset + 1];
					final Node exp = (Node) _symbol_exp.value;
					final Symbol e = _symbols[offset + 2];
					 exp.setEnd(e); return exp;
				}
			},
			new Action() {	// [70] procedure_expression = TOKEN_IDENTIFIER.name TOKEN_LPAR expression_part.ep TOKEN_RPAR.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					final Symbol _symbol_ep = _symbols[offset + 3];
					final NodeList ep = (NodeList) _symbol_ep.value;
					final Symbol e = _symbols[offset + 4];
					 	NodeId funct = procedureEnvironment.getVariable(name); 
																			return new NodeCallFct( name.getStart(), e.getEnd(), name, (TypeFunct)funct.getType(), ep);
				}
			},
			Action.NONE,  	// [71] expression_part = 
			new Action() {	// [72] expression_part = expression_list.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [73] expression_list = expression_list.list TOKEN_COMMA expression.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final Node list = (Node) _symbol_list.value;
					final Symbol _symbol_node = _symbols[offset + 3];
					final NodeExp node = (NodeExp) _symbol_node.value;
					 list.add(node); return list;
				}
			},
			new Action() {	// [74] expression_list = expression.node
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 1];
					final NodeExp node = (NodeExp) _symbol_node.value;
					 return new NodeList(node.getStart(), node.getEnd(), node);
				}
			},
			new Action() {	// [75] new_statement = TOKEN_NEW.b variable_access.v TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_v = _symbols[offset + 2];
					final NodeExp v = (NodeExp) _symbol_v.value;
					final Symbol e = _symbols[offset + 3];
					 return new NodeNew(b.getStart(), e.getEnd(), v);
				}
			},
			new Action() {	// [76] dispose_statement = TOKEN_DISPOSE.b variable_access.v TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_v = _symbols[offset + 2];
					final NodeExp v = (NodeExp) _symbol_v.value;
					final Symbol e = _symbols[offset + 3];
					 return new NodeDispose(b.getStart(), e.getEnd(), v);
				}
			},
			new Action() {	// [77] println_statement = TOKEN_PRINTLN.b expression.exp TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 3];
					 return new NodeOp(b.getStart(), e.getEnd(), "println", exp);
				}
			},
			new Action() {	// [78] readln_statement = TOKEN_READLN.b expression.exp TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 3];
					 return new NodeOp(b.getStart(), e.getEnd(), "readln", exp);
				}
			},
			new Action() {	// [79] return_statement = TOKEN_RETURN.b expression.exp TOKEN_SEMIC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 3];
					 return new NodeReturn(b.getStart(), e.getEnd(), exp);
				}
			},
			new Action() {	// [80] structured_statement = block.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [81] structured_statement = if_statement.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [82] structured_statement = while_statement.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Node n = (Node) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [83] structured_statement = switch_statement.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return n;
				}
			},
			new Action() {	// [84] if_statement = TOKEN_IF.b expression.exp TOKEN_THEN statement.stm1 TOKEN_ELSE.e statement.stm2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol _symbol_stm1 = _symbols[offset + 4];
					final Node stm1 = (Node) _symbol_stm1.value;
					final Symbol e = _symbols[offset + 5];
					final Symbol _symbol_stm2 = _symbols[offset + 6];
					final Node stm2 = (Node) _symbol_stm2.value;
					 return new NodeIf(b.getStart(), e.getEnd(), exp, stm1, stm2);
				}
			},
			new Action() {	// [85] if_statement = TOKEN_IF.b expression.exp TOKEN_THEN.e statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 3];
					final Symbol _symbol_stm = _symbols[offset + 4];
					final Node stm = (Node) _symbol_stm.value;
					 return new NodeIf(b.getStart(), e.getEnd(), exp, stm);
				}
			},
			new Action() {	// [86] while_statement = TOKEN_WHILE.b expression.exp TOKEN_DO statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol _symbol_stm = _symbols[offset + 4];
					final Node stm = (Node) _symbol_stm.value;
					 return new NodeWhile(b.getStart(), stmn.getEnd(), exp, stm);
				}
			},
			new Action() {	// [87] switch_statement = TOKEN_SWITCH.b expression.exp TOKEN_BEGIN case_statement_list.stm TOKEN_END.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol _symbol_stm = _symbols[offset + 4];
					final NodeList stm = (NodeList) _symbol_stm.value;
					final Symbol e = _symbols[offset + 5];
					 return new NodeSwitch(b.getStart(), e.getEnd(), exp, stm);
				}
			},
			new Action() {	// [88] case_statement_list = case_statement_list.list case_statement.cstmn case_default.cdef
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final NodeList list = (NodeList) _symbol_list.value;
					final Symbol _symbol_cstmn = _symbols[offset + 2];
					final NodeList cstmn = (NodeList) _symbol_cstmn.value;
					final Symbol _symbol_cdef = _symbols[offset + 3];
					final NodeCase cdef = (NodeCase) _symbol_cdef.value;
					 list.add(cstmn); list.add(cdef); return list;
				}
			},
			new Action() {	// [89] case_statement_list = case_statement.cstmn
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_cstmn = _symbols[offset + 1];
					final NodeList cstmn = (NodeList) _symbol_cstmn.value;
					 return new NodeList(cstmn.getStart(), cstmn.getEnd(), cstmn);
				}
			},
			new Action() {	// [90] case_statement = TOKEN_CASE.b identifier_list.list TOKEN_COLON.e statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_list = _symbols[offset + 2];
					final IdentifierList list = (IdentifierList) _symbol_list.value;
					final Symbol e = _symbols[offset + 3];
					final Symbol _symbol_stm = _symbols[offset + 4];
					final Node stm = (Node) _symbol_stm.value;
					 	
																			NodeList node_list = new NodeList(b.getStart(), e.getEnd());
																			for(String s : list)
																		         node_list.add(new NodeCase(s, stm));
																	      	return node_list;
				}
			},
			Action.NONE,  	// [91] case_default = 
			new Action() {	// [92] case_default = TOKEN_DEFAULT.b TOKEN_COLON statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_stm = _symbols[offset + 3];
					final Node stm = (Node) _symbol_stm.value;
					 return new NodeCase(b.getStart(), stmn.getEnd(), stm);
				}
			},
			new Action() {	// [93] ptr_access = expression.exp TOKEN_CIRC.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_exp = _symbols[offset + 1];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 2];
					 return new NodePtrAccess(exp.getStart(), e.getEnd(), exp);
				}
			},
			new Action() {	// [94] struct_access = variable_access.t TOKEN_DOT TOKEN_IDENTIFIER.field
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final NodeExp t = (NodeExp) _symbol_t.value;
					final Symbol field = _symbols[offset + 3];
					 return new NodeStructAccess(t.getStart(), field.getEnd(), field);
				}
			},
			new Action() {	// [95] array_access = variable_access.t TOKEN_LBRACKET expression.i TOKEN_RBRACKET.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final NodeExp t = (NodeExp) _symbol_t.value;
					final Symbol _symbol_i = _symbols[offset + 3];
					final NodeExp i = (NodeExp) _symbol_i.value;
					final Symbol e = _symbols[offset + 4];
					 return new NodeArrayAccess(t.getStart(), e.getEnd(), t, i);
				}
			},
			new Action() {	// [96] variable_access = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol name = _symbols[offset + 1];
					 return stackEnvironment.getVariable(name);
				}
			},
			new Action() {	// [97] variable_access = array_access.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final NodeArrayAccess n = (NodeArrayAccess) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [98] variable_access = struct_access.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final NodeStructAccess n = (NodeStructAccess) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [99] variable_access = ptr_access.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final NodePtrAccess n = (NodePtrAccess) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [100] expression = expression.e1 TOKEN_PLUS expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "+", e1, e2);
				}
			},
			new Action() {	// [101] expression = expression.e1 TOKEN_MINUS expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "-", e1, e2);
				}
			},
			new Action() {	// [102] expression = expression.e1 TOKEN_TIMES expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "*", e1, e2);
				}
			},
			new Action() {	// [103] expression = expression.e1 TOKEN_DIV expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "/", e1, e2);
				}
			},
			new Action() {	// [104] expression = TOKEN_MINUS.b expression.exp
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					 return new NodeOp(b.getStart(), exp.getEnd(), "-", e);
				}
			},
			new Action() {	// [105] expression = expression.e1 TOKEN_OR expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "||", e1, e2);
				}
			},
			new Action() {	// [106] expression = expression.e1 TOKEN_AND expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "&&", e1, e2);
				}
			},
			new Action() {	// [107] expression = expression.e1 TOKEN_LT expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "<", e1, e2);
				}
			},
			new Action() {	// [108] expression = expression.e1 TOKEN_LE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "<=", e1, e2);
				}
			},
			new Action() {	// [109] expression = expression.e1 TOKEN_GT expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), ">", e1, e2);
				}
			},
			new Action() {	// [110] expression = expression.e1 TOKEN_GE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), ">=", e1, e2);
				}
			},
			new Action() {	// [111] expression = expression.e1 TOKEN_EQ expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "==", e1, e2);
				}
			},
			new Action() {	// [112] expression = expression.e1 TOKEN_NE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp(e1.getStart(), e2.getEnd(), "!=", e1, e2);
				}
			},
			new Action() {	// [113] expression = TOKEN_NOT.b expression.exp
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					 return new NodeOp(b.getStart(), exp.getEnd(), "!", e);
				}
			},
			new Action() {	// [114] expression = TOKEN_LPAR.b expression.exp TOKEN_RPAR.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol b = _symbols[offset + 1];
					final Symbol _symbol_exp = _symbols[offset + 2];
					final NodeExp exp = (NodeExp) _symbol_exp.value;
					final Symbol e = _symbols[offset + 3];
					 exp.setPosition(b, e); return exp;
				}
			},
			new Action() {	// [115] expression = procedure_expression.p
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_p = _symbols[offset + 1];
					final Node p = (Node) _symbol_p.value;
					 return p;
				}
			},
			new Action() {	// [116] expression = variable_access.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final NodeExp v = (NodeExp) _symbol_v.value;
					 return v;
				}
			},
			new Action() {	// [117] expression = literal.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final NodeLiteral l = (NodeLiteral) _symbol_l.value;
					 return l;
				}
			},
			new Action() {	// [118] literal = TOKEN_LIT_INTEGER.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return new NodeLiteral(n.getStart(), n.getEnd(), new TypeInt((Integer)(n.value)), (Integer)(n.value));
				}
			},
			new Action() {	// [119] literal = TOKEN_LIT_STRING.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return new NodeLiteral(n.getStart(), n.getEnd(), new TypeString(), (String) (n.value));
				}
			},
			new Action() {	// [120] literal = TOKEN_TRUE.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return new NodeLiteral(n.getStart(), n.getEnd(), new TypeBoolean(), true);
				}
			},
			new Action() {	// [121] literal = TOKEN_FALSE.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return new NodeLiteral(n.getStart(), n.getEnd(), new TypeBoolean(), false);
				}
			},
			new Action() {	// [122] literal = TOKEN_NULL.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol n = _symbols[offset + 1];
					 return new NodeLiteral(n.getStart(), n.getEnd(), new TypePointer(n.getStart(), n.getEnd()), null);
				}
			}
		};

 
	report = new Events();
	stackEnvironment.pushEnvironment("Global");
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
